update main.nf
- add qza_table.view() since we got the error:
	Command error:
  /opt/conda/envs/qiime2-2020.8/lib/python3.6/site-packages/skbio/util/_testing.py:15: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
    import pandas.util.testing as pdt
  Traceback (most recent call last):
    File ".command.sh", line 18, in <module>
      unrarefied_table = Artifact.load('table.qza')
    File "/opt/conda/envs/qiime2-2020.8/lib/python3.6/site-packages/qiime2/sdk/result.py", line 66, in load
      archiver = archive.Archiver.load(filepath)
    File "/opt/conda/envs/qiime2-2020.8/lib/python3.6/site-packages/qiime2/core/archive/archiver.py", line 299, in load
      archive = cls.get_archive(filepath)
    File "/opt/conda/envs/qiime2-2020.8/lib/python3.6/site-packages/qiime2/core/archive/archiver.py", line 264, in get_archive
      raise ValueError("%s is not a QIIME archive." % filepath)
  ValueError: table.qza is not a QIIME archive.